import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import Hero from "../components/hero";
import About from "../components/about";
// import { api } from "../utils/api";
import Experience from "../components/Experience";
import Projects from "../components/projects";
import Contact from "../components/contact";
import TawkTo from "../components/Tawk";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="relative bg-gradient-to-t from-[#101212] to-[#08201D] text-white overflow-hidden dark">
        <Navbar />
        <Hero/>
        <About/>
        <Experience/>
        <Projects/>
        <Contact/>
        <TawkTo/>
      </section>
    </>
  );
};

export default Home;
